[build]
  publish = "build/web"
  command = "curl -fsSL https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.35.4-stable.tar.xz | tar -xJ && export PATH=\"$PATH:$(pwd)/flutter/bin\" && flutter config --enable-web && flutter pub get && echo 'SUPABASE_URL=https://iyvzsyvwczoprjmcjclq.supabase.co' > .env && echo 'SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5dnpzeXZ3Y3pvcHJqbWNqY2xxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NjYxMjQsImV4cCI6MjA3NDA0MjEyNH0.bI3fZFrcapzKNeyTCDw0E0VVSVxq0D_baMgcQo1A_wA' >> .env && flutter build web --release"

[build.environment]
  SUPABASE_URL = "https://iyvzsyvwczoprjmcjclq.supabase.co"
  SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5dnpzeXZ3Y3pvcHJqbWNqY2xxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NjYxMjQsImV4cCI6MjA3NDA0MjEyNH0.bI3fZFrcapzKNeyTCDw0E0VVSVxq0D_baMgcQo1A_wA"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
