name: kanso
description: A minimalist decluttering app inspired by Japanese Zen rock gardens
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  image_picker: ^1.0.4
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  supabase_flutter: ^2.0.0
  uuid: ^4.2.1
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
